{ var, ... }: {
  wayland.windowManager.hyprland.settings = {
    bind = [
      "${var.key.mainMod}, RETURN, exec, ${var.terminal}"
      "${var.key.mainMod}+${var.key.shiftMod}, F, exec, ${var.browser}"
      "${var.key.mainMod}+${var.key.shiftMod}, T, exec, ${var.fileManager}"
      "${var.key.mainMod}, R, exec, ${var.launcher}"
      "${var.key.mainMod}, P, exec, ${var.powermenu}"
      "${var.key.mainMod}, Q, killactive,"
      "${var.key.mainMod}+${var.key.altMod}, Q, exit,"
      "${var.key.mainMod}, E, togglefloating,"
      "${var.key.mainMod}+${var.key.shiftMod}, E, pin, active"
      "${var.key.mainMod}, X, togglesplit,"
      "${var.key.mainMod}, M, fullscreen, 0"
      "${var.key.mainMod}, H, movefocus, l"
      "${var.key.mainMod}, L, movefocus, r"
      "${var.key.mainMod}, K, movefocus, u"
      "${var.key.mainMod}, J, movefocus, d"
      "${var.key.mainMod}+${var.key.shiftMod}, H, movewindow, l"
      "${var.key.mainMod}+${var.key.shiftMod}, L, movewindow, r"
      "${var.key.mainMod}+${var.key.shiftMod}, K, movewindow, u"
      "${var.key.mainMod}+${var.key.shiftMod}, J, movewindow, d"
      "${var.key.mainMod}, 1, workspace, 1"
      "${var.key.mainMod}, 2, workspace, 2"
      "${var.key.mainMod}, 3, workspace, 3"
      "${var.key.mainMod}, 4, workspace, 4"
      "${var.key.mainMod}, 5, workspace, 5"
      "${var.key.mainMod}, 6, workspace, 6"
      "${var.key.mainMod}, 7, workspace, 7"
      "${var.key.mainMod}, 8, workspace, 8"
      "${var.key.mainMod}, 9, workspace, 9"
      "${var.key.mainMod}, 0, workspace, 10"
      "${var.key.mainMod} ${var.key.controlMod}, 1, movetoworkspacesilent, 1"
      "${var.key.mainMod} ${var.key.controlMod}, 2, movetoworkspacesilent, 2"
      "${var.key.mainMod} ${var.key.controlMod}, 3, movetoworkspacesilent, 3"
      "${var.key.mainMod} ${var.key.controlMod}, 4, movetoworkspacesilent, 4"
      "${var.key.mainMod} ${var.key.controlMod}, 5, movetoworkspacesilent, 5"
      "${var.key.mainMod} ${var.key.controlMod}, 6, movetoworkspacesilent, 6"
      "${var.key.mainMod} ${var.key.controlMod}, 7, movetoworkspacesilent, 7"
      "${var.key.mainMod} ${var.key.controlMod}, 8, movetoworkspacesilent, 8"
      "${var.key.mainMod} ${var.key.controlMod}, 9, movetoworkspacesilent, 9"
      "${var.key.mainMod} ${var.key.controlMod}, 0, movetoworkspacesilent, 10"
      "${var.key.mainMod} ${var.key.shiftMod}, 1, movetoworkspace, 1"
      "${var.key.mainMod} ${var.key.shiftMod}, 2, movetoworkspace, 2"
      "${var.key.mainMod} ${var.key.shiftMod}, 3, movetoworkspace, 3"
      "${var.key.mainMod} ${var.key.shiftMod}, 4, movetoworkspace, 4"
      "${var.key.mainMod} ${var.key.shiftMod}, 5, movetoworkspace, 5"
      "${var.key.mainMod} ${var.key.shiftMod}, 6, movetoworkspace, 6"
      "${var.key.mainMod} ${var.key.shiftMod}, 7, movetoworkspace, 7"
      "${var.key.mainMod} ${var.key.shiftMod}, 8, movetoworkspace, 8"
      "${var.key.mainMod} ${var.key.shiftMod}, 9, movetoworkspace, 9"
      "${var.key.mainMod} ${var.key.shiftMod}, 0, movetoworkspace, 10"
      "${var.key.mainMod} ${var.key.shiftMod}, S, movetoworkspace, special:magic"
      "${var.key.mainMod}, S, togglespecialworkspace, magic"

      "${var.key.altMod}, w, exec, ${var.change_wallpaper}"
      "${var.key.altMod}, b, exec, pkill waybar || waybar"
      ", PRINT, exec, hyprshot -m region"
    ];
    bindm = [
      "${var.key.mainMod}, mouse:272, movewindow"
      "${var.key.mainMod}, mouse:273, resizewindow"
    ];
    bindl = [
      ", XF86AudioNext, exec, playerctl next"
      ", XF86AudioPause, exec, playerctl play-pause"
      ", XF86AudioPlay, exec, playerctl play-pause"
      ", XF86AudioPrev, exec, playerctl previous"
      ", XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.05+ -l 1.0"
      ", XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.05-"
      ", XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
      ", XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"
      ", XF86MonBrightnessUp, exec, brightnessctl --class=backlight set 5%+"
      ", XF86MonBrightnessDown, exec, brightnessctl --class=backlight set 5%-"
    ];
  };
}
